// generated by nuxt-seo-kit
import type { ModuleOptions } from 'nuxt-seo-kit'
declare module '#nuxt-seo-kit/config' {
  export const splash: true | ModuleOptions['splash']
  export const siteName: "August Robotics - the world's leading autonomous commercial robotics company" | ModuleOptions['siteName']
  export const siteDescription: "We automate dirty, dangerous and dull tasks all over the world. " | ModuleOptions['siteDescription']
  export const siteImage: undefined | ModuleOptions['siteImage']
  export const siteUrl: "https://example.com" | ModuleOptions['siteUrl']
  export const titleSeparator: "|" | ModuleOptions['titleSeparator']
  export const trailingSlash: true | ModuleOptions['trailingSlash']
  export const language: "en" | ModuleOptions['language']
  export const indexable: false | ModuleOptions['indexable']
}
