// generated by nuxt-simple-sitemap
import type { ModuleOptions } from 'nuxt-simple-sitemap'
declare module '#nuxt-simple-sitemap/config' {
  export const include: ["/**"] | ModuleOptions['include']
  export const hostname: "https://augustrobotics.com" | ModuleOptions['hostname']
  export const trailingSlash: true | ModuleOptions['trailingSlash']
  export const enabled: true | ModuleOptions['enabled']
  export const urls: [{"url":"/"},{"url":"/news/"},{"url":"/about/"},{"url":"/diego/"},{"url":"/lionel/"},{"url":"/careers/"},{"url":"/contact/"},{"url":"/news/22-march-2023/"}] | ModuleOptions['urls']
  export const defaults: {} | ModuleOptions['defaults']
  export const devPreview: true | ModuleOptions['devPreview']
  export const inferStaticPagesAsRoutes: true | ModuleOptions['inferStaticPagesAsRoutes']
}
